path: C:\Users\Aman's Laptop\Documents\DNNProjects\Face_Detection\archive (2)  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: face